### ISSUE TITLE
Need to update mauth-client to include query parameters in mAuth signature

### ISSUE THREAD

**Issue by raroskar-mdsol** [mdsol/mauth-jvm-clients#65]
Background
Medicines and Healthcare products Regulatory Agency (MHRA)'s review of Medidata Products, they observed, **
The protocol used to authenticate remote applications, mAuth, was used inconsistently in that important elements of the message were excluded from the signature (specifically the use of function verbs in URL queries), thus functions were not authenticated, which could introduce the risk that functions could be substituted (e.g. overwrite data instead of append to a record). **

What is expected?

- mauth-client has new mauth request signing algorithm (MWSV2) , which will have authentication header looking similar to original 'x-mws-authentication' header and in addition it will append the query params k-v pairs, sorted ascending by key.
- mauth-client should maintain backwards compatibility i.e. original MWS (current signature algorithm) should still be available and usable.
- mauth-client must be able to sign with both MWS and MWSV2 for requests.
- mauth-client should have sufficient logging such that it will be easy to figure out how many (and who) requests are still using MWS vs MWSV2 in any given time period

**Comment by jatcwang** [comment]
Most of these are addressed in https://github.com/mdsol/mauth-jvm-clients/pull/94

@bgong-mdsol After the current Pr is merged should we add logging when a mauth v1 only request is received? (Addressing the last point)

**Comment by bgong-mdsol** [comment]
> Most of these are addressed in #94
> 
> @bgong-mdsol After the current Pr is merged should we add logging when a mauth v1 only request is received? (Addressing the last point)

@jatcwang we add logging for the both  in https://github.com/mdsol/mauth-jvm-clients/blob/72583e5ccd2d10fefc747111930732c5adc49aad/modules/mauth-authenticator/src/main/java/com/mdsol/mauth/RequestAuthenticator.java#L93

**Comment by jatcwang** [comment]
What's the log message if both v1 and v2 headers are provided?

**Comment by bgong-mdsol** [comment]
> What's the log message if both v1 and v2 headers are provided?
> 
> @jatcwang Yes, add the mauth version (MWS or MWSV2) in the logging https://github.com/mdsol/mauth-jvm-clients/blob/72583e5ccd2d10fefc747111930732c5adc49aad/modules/mauth-authenticator/src/main/java/com/mdsol/mauth/RequestAuthenticator.java#L93~#L95

If both v1 and v2 headers are provided, Authenticator does authenticate for V2 (higher version as design), only V2 related information will be wrote into log.

**Comment by austek** [comment]
I believe, all points are addressed for this issue

**Comment by jatcwang** [comment]
Yeap can be closed. Thanks for your work @bgong-mdsol @austek
